apiVersion: v1
kind: Service
metadata:
  name: user-client
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    web-client: user-client

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-client
spec:
  selector:
    matchLabels:
      web-client: user-client
  template:
    metadata:
      labels:
        web-client: user-client
        system: client
    spec:
      containers:
      - name: user-client
        image: pesho1/carrentalsystem-user-client
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
