apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statistics-database
spec:
  serviceName: statistics-database
  selector:
    matchLabels:
      database: statistics
  template:
    metadata:
      labels:
        database: statistics
        system: database
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: statistics-database
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: environment-secrets
                key: statistics-database-sa-password
        volumeMounts:
          - name: statistics-database-data
            mountPath: /var/opt/mssql
      volumes:
      - name: statistics-database-data
        persistentVolumeClaim:
          claimName: statistics-database-data
