apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-service-data
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany 
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  ports:
  - port: 5001
    targetPort: 80
  selector:
    web-service: identity

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      web-service: identity
  template:
    metadata:
      labels:
        web-service: identity
        system: server
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                web-service: identity
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: identity-service
        image: ivaylokenov/carrentalsystem-identity-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: ApplicationSettings__Secret
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: security-token-secret
        - name: ApplicationSettings__SeedInitialData
          valueFrom:
            configMapKeyRef:
              name: environment-settings
              key: seed-initial-data
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: identity-service-connection-string
        - name: IdentitySettings__AdminPassword
          valueFrom:
            secretKeyRef:
              name: environment-secrets
              key: admin-password
        volumeMounts:
        - name: identity-service-data
          mountPath: /root/.aspnet/DataProtection-Keys
      volumes:
      - name: identity-service-data
        persistentVolumeClaim:
          claimName: identity-service-data
