apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-settings
data:
  seed-initial-data: "True"
  event-bus-user: rabbitmquser
  event-bus-host: event-bus
  notifications-allowed-origins: http://localhost
  admin-identity-endpoint: http://identity-service:5001
  admin-dealers-endpoint: http://dealers-service:5002
  admin-statistics-endpoint: http://statistics-service:5003
  watchdog-identity-health: http://identity-service:5001/health
  watchdog-dealers-health: http://dealers-service:5002/health
  watchdog-statistics-health: http://statistics-service:5003/health
  watchdog-notifications-health: http://notifications-service:5004/health
  watchdog-admin-health: http://admin-client:5000/health

---

apiVersion: v1
kind: Secret
metadata:
  name: environment-secrets
data:
    car-rental-system-database-sa-password: Y3JzRGF0YWJhc2VQYXNzd29yZDEyIUA=
    security-token-secret: UzBNMyBNNEcxQyBVTjFDMFJOUyBHM04zUjRUM0QgVEgxUyBTM0NSM1Q=
    admin-password: YWRtaW5wYXNzMTIh
    identity-service-connection-string: U2VydmVyPWNhci1yZW50YWwtc3lzdGVtLWRhdGFiYXNlO0RhdGFiYXNlPUNhclJlbnRhbElkZW50aXR5RGF0YWJhc2U7VXNlciBJZD1zYTsgUGFzc3dvcmQ9Y3JzRGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
    event-bus-password: cmFiYml0bXFQYXNzd29yZDEyIQ==
    dealers-service-connection-string: U2VydmVyPWNhci1yZW50YWwtc3lzdGVtLWRhdGFiYXNlO0RhdGFiYXNlPUNhclJlbnRhbERlYWxlcnNEYXRhYmFzZTtVc2VyIElkPXNhOyBQYXNzd29yZD1jcnNEYXRhYmFzZVBhc3N3b3JkMTIhQDtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZQ==
    dealers-service-cron-jobs-connection-string: U2VydmVyPWNhci1yZW50YWwtc3lzdGVtLWRhdGFiYXNlO0RhdGFiYXNlPUNhclJlbnRhbERlYWxlcnNDcm9uSm9ic0RhdGFiYXNlO1VzZXIgSWQ9c2E7IFBhc3N3b3JkPWNyc0RhdGFiYXNlUGFzc3dvcmQxMiFAO011bHRpcGxlQWN0aXZlUmVzdWx0U2V0cz10cnVl
    statistics-service-connection-string: U2VydmVyPWNhci1yZW50YWwtc3lzdGVtLWRhdGFiYXNlO0RhdGFiYXNlPUNhclJlbnRhbFN0YXRpc3RpY3NEYXRhYmFzZTtVc2VyIElkPXNhOyBQYXNzd29yZD1jcnNEYXRhYmFzZVBhc3N3b3JkMTIhQDtNdWx0aXBsZUFjdGl2ZVJlc3VsdFNldHM9dHJ1ZQ==
    statistics-service-cron-jobs-connection-string: U2VydmVyPWNhci1yZW50YWwtc3lzdGVtLWRhdGFiYXNlO0RhdGFiYXNlPUNhclJlbnRhbFN0YXRpc3RpY3NDcm9uSm9ic0RhdGFiYXNlO1VzZXIgSWQ9c2E7UGFzc3dvcmQ9Y3JzRGF0YWJhc2VQYXNzd29yZDEyIUA7TXVsdGlwbGVBY3RpdmVSZXN1bHRTZXRzPXRydWU=
